
const actionTypes = {
    SET_NETWORK: 'SET_NETWORK',
    ADD_WALLET: 'ADD_WALLET',
    REMOVE_WALLET: 'REMOVE_WALLET',
    SET_DEFAULT_WALLET: 'SET_DEFAULT_WALLET',
    REMOVE_DEFAULT_WALLET: 'REMOVE_DEFAULT_WALLET',
    SET_ETH_BALANCE: "SET_ETH_BALANCE",
    SET_BLC_BALANCE: "SET_BLC_BALANCE",
    SHOW_MODAL_CREATE_WALLET: "SHOW_MODAL_CREATE_WALLET",
    HIDE_MODAL_CREATE_WALLET: "HIDE_MODAL_CREATE_WALLET",  
    SHOW_MODAL_DEFAULT_WALLET_SETTINGS: "SHOW_MODAL_DEFAULT_WALLET_SETTINGS",
    HIDE_MODAL_DEFAULT_WALLET_SETTINGS: "HIDE_MODAL_DEFAULT_WALLET_SETTINGS",  
    SHOW_MODAL_RESTORE_WALLET: "SHOW_MODAL_RESTORE_WALLET",
    HIDE_MODAL_RESTORE_WALLET: "HIDE_MODAL_RESTORE_WALLET",
    SHOW_MODAL_GENERATE_WALLET: "SHOW_MODAL_GENERATE_WALLET",
    HIDE_MODAL_GENERATE_WALLET: "HIDE_MODAL_GENERATE_WALLET",
    SHOW_MODAL_SELECT_ANOTHER_WALLET: "SHOW_MODAL_SELECT_ANOTHER_WALLET",
    HIDE_MODAL_SELECT_ANOTHER_WALLET: "HIDE_MODAL_SELECT_ANOTHER_WALLET", 
};
    
export default actionTypes;